language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: Kpl3b4KjhACGN1juT+C+UbdScRl/MZMGicU5dv5GzygvyDnd/oGnVjm0AD8yliJgMjSwjLKZQj7oQaXf/cE0Wvumx3XvILxxaH+KQUErzpeTgMHD6uC7uijtPgucHuPJZw4X1ckITlTk02/LIZmivbs4akY5Nre3Mdoz3s2bo4Zn6LmNnPZIJ7VWvM0YjIzlQNYSZILZ3FtcLOQjtQ2KzyC55pIbxqpzZOI7dTZDWmTZ6InRx7Z2KlfzeVKcy5O+MaW4kdKyw+bjk2lgDcNmiC1BYg9D8IhEvZNWSpZdiy7ckcofGrCrePAvxI5Gj8mP4953NQ0QKeAW8MQUiXsogCQydAmKNRhGGDbBXP0Q3zu4xhBKmlLLsYdN5gTeMHqfDQX5u/UXuYaTD0ahptVi0CbmbXL5qfR4IwoxNJQziW33+TVOLZ/opbZYuEe+hjzEU1mXiy1VSeAF0RgVSvEwYiWv0IjNFaW99lQ+IwbG40aL+eBV96YGZFGEFC+NS/UE4KagMYpqR+3imjWl4MuwaJbh7Qp1hHuM8sygZqAGYbUdiIDKsi+JZg0RtZkP1e8AK2lKz4jzWZnJokcNbQItFPx1SSYrBI4jpSrBCRThjAxd6uQ/Wj+Q/gpQqgcrA3LhVoDi1KeccgATjJ55a8Ly7DP4yfeq7TiO18Cn4OD1tqw=
